name: GitHubActionDemo

on: 
  push:
    branches:
    - main
    paths-ignore: 
    - ".git/**"
    - "hello-world-docker-action/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environament to deploy to"
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was triggered by ${{ github.event_name }} event "
      - run: echo "The name of the branch is ${{ github.ref}} "
      - uses: actions/checkout@v4.2.2
      - name: List all files for the repository
        run: |
          echo "The ${{ github.repository }} repository constains the following files:"
          tree
  
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [Build]
    environment: Test

    steps:
      - run: echo 'Testing ...'

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [Build]
    environment: Load-Test

    steps:
      - run: echo 'Testing ...'

  Production:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Production'
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: "https://writeabout.net"

    steps:
      - run: |
          echo "Step 1 deploying ..."
          sleep 10
      - run: |
          echo "Step 2 deploying ..."
          sleep 10
      - run: |
          echo "Step 3 deploying ..."
          sleep 10
      - run: |
          echo "Step 4 deploying ..."
          sleep 10
      - run: |
          echo "Step 5 deploying ..."
          sleep 10
    

    
