name: GitHubActionDemo

on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was triggered by ${{ github.event_name }} event "
      - run: echo "The job was triggered by ${{ github.ref}} event "
      
