name: GitHubActionDemo

on: 
  push:
    branches:
    - main
    paths-ignore: 
    - ".git/**"
    - "hello-world-docker-action/**"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was triggered by ${{ github.event_name }} event "
      - run: echo "The name of the branch is ${{ github.ref}} "
      - uses: actions/checkout@v4.2.2
      - name: List all files for the repository
        run: |
          echo "The ${{ github.repository }} repository constains the following files:"
          tree
