name: Reusabe workflow

on: 
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true
        default: 'World'
    outputs:
      current-time:
        description: "Greeting time"
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.current-time }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet}}"
      - name: Setup current time variable
        id: time
        run: echo "current-time=$(date)" >> $GITHUB_OUTPUT
        
